name: PyPI release

on: [push]

jobs:
  pypi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        setup: ["setup", "setup_meta"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: python -m pip install --upgrade setuptools wheel twine
      - name: Build
        run: |
          python ${{ matrix.setup }}.py sdist bdist_wheel
          twine check dist/*
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          verbose: true
          user: __token__
          password: ${{ secrets[format('pypi_password_{0}', matrix.setup)] }}
